---
env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:prettier/recommended
  - prettier
  - react-app
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - react
  - react-hooks
  - sonarjs
rules:
  prettier/prettier: error
  no-console: error
  '@typescript-eslint/no-floating-promises': warn
  '@typescript-eslint/prefer-regexp-exec': off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-unsafe-assignment': warn
  '@typescript-eslint/no-unsafe-return': warn
  '@typescript-eslint/no-unsafe-member-access': warn
  'sonarjs/cognitive-complexity': warn
  'sonarjs/no-duplicate-string': warn
  'sonarjs/no-small-switch': off
  '@typescript-eslint/no-explicit-any': off
  'react-hooks/exhaustive-deps': error
  '@typescript-eslint/no-misused-promises': off
  '@typescript-eslint/ban-ts-comment': warn # must be deleted
  'react/prop-types': off
  '@typescript-eslint/no-empty-function': off
  'react/react-in-jsx-scope': off
  '@typescript-eslint/ban-types': ['error', { extendDefaults: true, types: { '{}': false } }]
