import { Column } from '@/models/customer-info/CustomerInfo';
import { ErrLogData, MobMasterData, MobileData, PaxData, RelationData } from '@/models/oneId/OneIdInfo';

const oneIdPaxColumn: Column[] = [
  { headerName: 'NO', field: 'no' },
  { headerName: 'OneID번호', field: 'oneIdNm' },
  { headerName: 'PNR번호', field: 'pnrNm' },
  { headerName: 'UCIID', field: 'uciid' },
  { headerName: 'PotentialId', field: 'potentialId' },
  { headerName: '사용여부', field: 'useYn' },
  { headerName: 'Skypass회원번호', field: 'skypassNm' },
  { headerName: '최초생성일시', field: 'createDate' },
  { headerName: '최종갱신일시', field: 'updateDate' },
];

const onIdPaxData: PaxData[] = [
  {
    no: '1',
    oneIdNm: 'Jan 14, 2023',
    pnrNm: 'FUK-ICN',
    uciid: '1',
    potentialId: '1',
    useYn: '1',
    skypassNm: '1',
    createDate: '1',
    updateDate: '1',
  },
  {
    no: '1',
    oneIdNm: 'Jan 14, 2023',
    pnrNm: 'FUK-ICN',
    uciid: '1',
    potentialId: '1',
    useYn: '1',
    skypassNm: '1',
    createDate: '1',
    updateDate: '1',
  },
  {
    no: '1',
    oneIdNm: 'Jan 14, 2023',
    pnrNm: 'FUK-ICN',
    uciid: '1',
    potentialId: '1',
    useYn: '1',
    skypassNm: '1',
    createDate: '1',
    updateDate: '1',
  },
  {
    no: '1',
    oneIdNm: 'Jan 14, 2023',
    pnrNm: 'FUK-ICN',
    uciid: '1',
    potentialId: '1',
    useYn: '1',
    skypassNm: '1',
    createDate: '1',
    updateDate: '1',
  },
  {
    no: '1',
    oneIdNm: 'Jan 14, 2023',
    pnrNm: 'FUK-ICN',
    uciid: '1',
    potentialId: '1',
    useYn: '1',
    skypassNm: '1',
    createDate: '1',
    updateDate: '1',
  },
];
const reason = [
  { value: '0', text: '전체' },
  { value: '1', text: 'KOM' },
  { value: '2', text: 'ENM' },
  { value: '3', text: 'DOB' },
  { value: '4', text: 'MOB' },
  { value: '5', text: 'EML' },
  { value: '6', text: 'REU' },
  { value: '7', text: 'PSP' },
];

const historyColumn: Column[] = [
  { headerName: 'No', field: 'ss' },
  { headerName: 'OneID번호', field: 'ss' },
  { headerName: 'OneID변경이유코드', field: 'ss' },
  { headerName: '변경전OneID유형코드', field: 'ss' },
  { headerName: '변경후OneID유형코드', field: 'ss' },
  { headerName: '변경전OneID상태코드', field: 'ss' },
  { headerName: '변경후OneID상태코드', field: 'ss' },
  { headerName: '변경전OneID최종변경Channel코드', field: 'ss' },
  { headerName: '변경후OneID최종변경Channel코드', field: 'ss' },
  { headerName: '변경전OneID최종변경관련번호', field: 'ss' },
  { headerName: '변경후OneID최종변경관련번호', field: 'ss' },
  { headerName: '변경전OneID최종변경UCIID', field: 'ss' },
  { headerName: '변경후OneID최종변경UCIID', field: 'ss' },
  { headerName: '변경전영문FirstName', field: 'ss' },
  { headerName: '변경후영문FirstName', field: 'ss' },
  { headerName: '변경전영문LastName', field: 'ss' },
  { headerName: '변경후영문LastName', field: 'ss' },
  { headerName: '변경전휴대전화번호정보', field: 'ss' },
  { headerName: '변경후휴대전화번호정보', field: 'ss' },
  { headerName: '변경전E-Mail주소', field: 'ss' },
  { headerName: '변경후E-Mail주소', field: 'ss' },
  { headerName: '변경전출생일자V', field: 'ss' },
  { headerName: '변경후출생일자V', field: 'ss' },
  { headerName: '변경전한글FirstName', field: 'ss' },
  { headerName: '변경후한글FirstName', field: 'ss' },
  { headerName: '변경전한글LastName', field: 'ss' },
  { headerName: '변경후한글LastName', field: 'ss' },
  { headerName: '변경전영문Soundex값', field: 'ss' },
  { headerName: '변경후영문Soundex값', field: 'ss' },
  { headerName: '변경전휴대전화정보Hash값', field: 'ss' },
  { headerName: '변경후휴대전화정보Hash값', field: 'ss' },
  { headerName: '변경전E-Mail주소Hash값', field: 'ss' },
  { headerName: '변경후E-Mail주소Hash값', field: 'ss' },
  { headerName: '변경전여권국적ISO3Letter국가코드', field: 'ss' },
  { headerName: '변경후여권국적ISO3Letter국가코드', field: 'ss' },
  { headerName: '변경전여권만료일자V', field: 'ss' },
  { headerName: '변경후여권만료일자V', field: 'ss' },
  { headerName: '최초생성일시', field: 'ss' },
  { headerName: '최종갱신일시', field: 'ss' },
];
const mobileColumn: Column[] = [
  { headerName: 'No', field: 'no' },
  { headerName: '대리점추정휴대전화번호정보', field: 'presumeNum' },
  { headerName: '대리점추정휴대전화번호정보Hash값', field: 'presumeNumHash' },
  { headerName: '사용여부', field: 'useYn' },
];
const mobileData: MobileData[] = [
  {
    no: '1',
    presumeNum: 'asdfas',
    presumeNumHash: 'asdfdafdsaf',
    useYn: 'Y',
  },
  {
    no: '2',
    presumeNum: '',
    presumeNumHash: '',
    useYn: 'Y',
  },
  {
    no: '3',
    presumeNum: '',
    presumeNumHash: '',
    useYn: 'N',
  },
];

const mobMasterColumn: Column[] = [
  { headerName: 'No', field: 'no' },
  { headerName: 'OneID번호', field: 'oneId' },
  { headerName: '영문FirstName', field: 'firstNameE' },
  { headerName: '영문LastName', field: 'lastNameE' },
  { headerName: '휴대전화번호정보', field: 'phoneNum' },
  { headerName: 'E-Mail주소', field: 'eMailAdr' },
  { headerName: '출생일자V', field: 'birth' },
  { headerName: '한글FirstName', field: 'firstNameK' },
  { headerName: '한글LastName', field: 'lastNameK' },
  { headerName: '성별코드', field: 'gender' },
  { headerName: '대리점추정코드', field: 'presumeCode' },
];

const mobMasterData: MobMasterData[] = [
  {
    no: '1',
    oneId: '원아이디',
    firstNameE: 'LEE',
    lastNameE: 'GEONIL',
    phoneNum: '010-1111-2222',
    eMailAdr: '1234@kalmate.net',
    birth: '2023-10-35',
    firstNameK: '이',
    lastNameK: '건일',
    gender: 'M',
    presumeCode: '추정코드',
  },
];

const relationColumn: Column[] = [
  { headerName: 'No', field: 'no' },
  { headerName: '병합TargetOneID번호', field: 'targetOneId' },
  { headerName: '병합SourceOneID번호', field: 'sourceOneId' },
  { headerName: 'Skypass회원번호', field: 'skypassNum' },
  { headerName: 'Skypass회원번호(PAX)', field: 'skypassNumPax' },
  { headerName: '영문FirstName', field: 'firstNameE' },
  { headerName: '영문LastName', field: 'lastNameE' },
  { headerName: '한글FirstName', field: 'firstNameK' },
  { headerName: '한글LastName', field: 'lastNameK' },
  { headerName: 'E-Mail주소', field: 'eMailAdr' },
  { headerName: '휴대전화번호정보', field: 'phoneNum' },
  { headerName: '출생일자V', field: 'birth' },
  { headerName: '최초생성일시', field: 'createDate' },
  { headerName: '최종갱신일시', field: 'updateDate' },
];

const relationData: RelationData[] = [
  {
    no: '1',
    targetOneId: '타겟원아이디',
    sourceOneId: '소스원아이디',
    firstNameE: 'LEE',
    lastNameE: 'GEONIL',
    firstNameK: '이',
    lastNameK: '건일',
    eMailAdr: '1234@kalmate.net',
    phoneNum: '010-1111-2222',
    birth: '2023-10-35',
    createDate: '2023-10-14',
    updateDate: '2023-10-14',
  },
];

// OneID 에러 이력 페이지 컬럼명
const errLogColumn: Column[] = [
  { headerName: 'No', field: 'no' },
  { headerName: '에러코드', field: 'errCode' },
  { headerName: '상세에러코드', field: 'errCodeDtl' },
  { headerName: 'OneID등록Channel코드', field: 'oneIdChCode' },
  { headerName: 'PNR/Skypass번호', field: 'pnrSkypass' },
  { headerName: 'SKYPASS 액션', field: 'skypassAct' },
  { headerName: 'ODS Header', field: 'odsHeader' },
  { headerName: 'ODS M_GID', field: 'odsMGid' },
  { headerName: 'UCIID', field: 'uciid' },
  { headerName: '상세내역', field: 'detailLog' },
  { headerName: '처리여부', field: 'processYn' },
  { headerName: '최초생성일시', field: 'createDate' },
  { headerName: '최종갱신일시', field: 'updateDate' },
];

const errLogData: ErrLogData[] = [
  {
    no: '1',
    errCode: 'error1',
    errCodeDtl: 'error1-1',
    oneIdChCode: 'oneId 채널 코드',
    pnrSkypass: 'pnrsky-1',
    skypassAct: '액션',
    odsHeader: 'odsH',
    odsMGid: 'odsMGid',
    uciid: 'uciid',
    detailLog: '상세내역',
    processYn: 'Y',
    createDate: '2023-10-26',
    updateDate: '2023-10-26',
  },
];

export {
  onIdPaxData,
  oneIdPaxColumn,
  reason,
  historyColumn,
  mobileColumn,
  mobileData,
  mobMasterColumn,
  mobMasterData,
  relationColumn,
  relationData,
  errLogColumn,
  errLogData,
};
